
#
# DELIMITATORE
#

DELIMITER $

#
#	PROCEDURE INSERIMENTO , CANC , E AGGIORNAMENTO TABELLA UTENTE
#


CREATE PROCEDURE aggiungi_utente( IN EMAIL VARCHAR(100), IN PASSWORD VARCHAR(100) ) 
	BEGIN
		INSERT INTO Utente(email,password) value ( EMAIL,PASSWORD);
	END $ 


CREATE PROCEDURE cancella_utente(IN EMAIL VARCHAR(100) )
	BEGIN
		DELETE FROM Utente where email = EMAIL ;
	END $


CREATE PROCEDURE aggiorna_email (IN EMAILVECCHIA VARCHAR(100) , IN EMAILNUOVA VARCHAR(100) )
	BEGIN
		UPDATE Utente SET email = EMAILNUOVA WHERE email = EMAILVECCHIA ;
	END $

CREATE PROCEDURE aggiorna_password(IN PASSWORD VARCHAR(100) , IN EMAIL VARCHAR(100) )
	BEGIN
		UPDATE Utente SET password = PASSWORD WHERE email = EMAIL ;
	END $

CREATE PROCEDURE aggiorna_tipo_attivo( IN EMAIL VARCHAR(100) )
	BEGIN 
		UPDATE Utente SET tipo = 'ATTIVO' WHERE email = EMAIL ;
	END $

CREATE PROCEDURE aggiorna_tipo_passivo( IN EMAIL VARCHAR(100) )
	BEGIN 
		UPDATE Utente SET tipo = 'PASSIVO' WHERE email = EMAIL ;
	END $


CREATE PROCEDURE aggiorna_tipo( IN EMAIL VARCHAR(100) , IN TIPO VARCHAR(10) )
	BEGIN 
		UPDATE Utente SET tipo = TIPO WHERE email = EMAIL ;
	END $



#
#	PROCEDURE CRUD ANAGRAFICA
#

CREATE PROCEDURE aggiungi_anagrafica 

(
	IN IDUTENTE INT,
	IN NOME  VARCHAR(100),
	IN COGNOME VARCHAR(100),
	IN CF VARCHAR(100),
	IN DATADINASCITA DATE,
	IN LUOGODINASCITA VARCHAR(100),
	IN NAZIONE VARCHAR(100)
)

	BEGIN
		INSERT INTO Anagrafica value (IDUTENTE,NOME,COGNOME,CF,DATADINASCITA,LUOGODINASCITA,NAZIONE) ;
	END $	





CREATE PROCEDURE cancella_anagrafica ( IN IDUTENTE INT )
	BEGIN
	DELETE FROM Anagrafica WHERE id_utente = IDUTENTE ;
	END $


#PROCEDURE PER AGGIORNAMENTO

#UPDATE NOME

CREATE PROCEDURE aggiorna_nome (IN NUOVONOME VARCHAR(100) , IN IDUTENTE INT )
	BEGIN
	UPDATE Anagrafica SET nome= NUOVONOME WHERE id_utente = IDUTENTE ;
	END $


#UPDATE COGNOME

CREATE PROCEDURE aggiorna_cognome(IN NUOVOCOGNOME VARCHAR(100), IN IDUTENTE INT)
	BEGIN
        UPDATE Anagrafica SET cognome= NUOVOCOGNOME WHERE id_utente = IDUTENTE ;
        END $


#UPDATE CODICE FISCALE

CREATE PROCEDURE aggiorna_cf ( IN NUOVOCF VARCHAR(100) , IN IDUTENTE INT )
        BEGIN
        UPDATE Anagrafica SET cf = NUOVOCF WHERE id_utente = IDUTENTE ;
        END $


#UPDATE DATA DI NASCITA

CREATE PROCEDURE aggiorna_data_nascita (IN NUOVADATA Date, IN IDUTENTE INT )
        BEGIN
        UPDATE Anagrafica SET data_nascita= NUOVADATA WHERE id_utente = IDUTENTE ;
        END $


#UPDATE LUOGO DI NASCITA

CREATE PROCEDURE aggiorna_luogo_nascita(IN NUOVOLUOGO VARCHAR(100), IN IDUTENTE INT)
        BEGIN
        UPDATE Anagrafica SET luogo_nascita = NUOVOLUOGO WHERE id_utente = IDUTENTE;
        END $


#UPDATE NAZIONE
CREATE PROCEDURE aggiorna_nazionalita (IN NUOVANAZIONE VARCHAR(100), IN IDUTENTE INT)
        BEGIN
        UPDATE Anagrafica SET nazionalita = NUOVANAZIONE WHERE id_utente = IDUTENTE ;
        END $





